### ISSUE TITLE
Model: Log

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#10]

**Comment by stylesuxx** [comment]
@cswertz Regarding the Log: In LearningUnit we have a field with User, since this is versioned I think we do not really need *dateedited_learningunit*, similarly we could add userID to KnowledgeUnit too and could get rid of *dateedited_knowledgeunit*. I would also omit the course related fields, since we do not have courses yet.

With all of this changes, Log would basically just be an access Log.

Could you also please explain the *users_role* field there? What should it log exactly?

**Comment by cswertz** [comment]
Learning Units are not versioned. But yes: The dateedited - fields are there because I designed those double keys, which are no longer present. Thus the ID should do. We can keep the course id - courses will be the very next developing step after the current ones. Thus it will be needed soon. But yes: Log should basically be an access log, but I want to know if the user just viewed or actually edited something. I'm not sure if I can figure that out without the dates in the log.
In users_role the active role of the user should be stored. A teacher might change to a student role in order to see his course from a student perspective and so on. 
 ths users_role -

**Comment by cswertz** [comment]
While talking about the log: I just did a paper on learning analytics and argued that any user should be able to turn logging and delete existing logs at any time. The later one will require a log editor, which is not part of the plan yet. But for the first one, a "do not log my date" - entry needs to be added to the comment in the privacylevel - field in users table. Maybe 0 for that would be good. In that case the log entries should only be written if privacylevel > 0. I'll change the comment.
BTW: I assume the application at large does not need apache or node logs as well?

**Comment by stylesuxx** [comment]
> A teacher might change to a student role in order to see his course from a student perspective and so on.

We discussed the roles in a different ticket. I am not sure how this role switch should exactly work with a global role system.

A user can have multiple roles of which each roles has multiple permissions.

When a teacher now removes the teacher role from himself, how will he be able to add it again?

> Maybe 0 for that would be good. In that case the log entries should only be written if privacylevel > 0
Yes, that is no problem.

> BTW: I assume the application at large does not need apache or node logs as well?
No, we can disable the apache logs completely - should be enough to disable the access log. And no - I do not need to log anything in Node.

**Comment by stylesuxx** [comment]
I think it would make sense to make a relation from log to role, so we have a snapshot of the roles the user had, at the moment the log entry was made - what do you think @cswertz ?

**Comment by cswertz** [comment]
@stylesuxx Convincing simple. Good idea - thx!

**Comment by cswertz** [comment]
@stylesuxx All foreign keys in 210-LogUser.js are set to cascade instead of restrict in the ERS. First, I came across a thinking mistake of myself: If a KU or LU is deleted, the log entry may still be kept (and the other way round) if we use autoincrement on the ID of the KnowledgeUnit . Thus I removed the foreign keys for KnowledgeUnitID and LearningUnitID from ERS and ORM. Second I adjusted the ERS to the ORM (Cascade for UserId).

**Comment by cswertz** [comment]
@stylesuxx DATE changed to DATETIME

**Comment by cswertz** [comment]
added updatedAt
added  unique: 'id' 'createdAt',

**Comment by cswertz** [comment]
@stylesuxx Sorry - but on second thought the UserLogRole table does not make sense. At access a user can have one active role - but not many. He might have the right to switch to another role - but he can not use more than one active role. Removed LogUserRole from ERS. No migrations present, so none deleted. No seeders present so none deleted. No model present so none deleted. Model for LogUser updated.

**Comment by stylesuxx** [comment]
Hmmm, then we still need to discuss the Role Model. I was under the impression, that a user can have multiple roles at the same time. If a user can switch between roles, we need a mechanism to store which role he has currently and which roles he is allowed to switch to.
