### ISSUE TITLE
unique keys

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#112]
In CapabilityLanguage the unique key     

unique: 'capabilityIdlanguageId',

is set twice. Additionally, the first letter is not a capital letter, while a capital letter is used in the declaration. 

Questions:
1) Should all columns use small letters as first letter (this is mostly the case)?
2) Is it necessary to declare unique keys on two columns for each column?

**Comment by stylesuxx** [comment]
Yes, they together are the unique key (composed key). capability can be there multiple times, language can be there mutliple times. together they can only be there once. all composed keys are lower case. Uppercase references are referencing actual entities. For example: CapabilityId is first case uppercase because it references a Capability entity, vocable is lower case since it is only an attribute.

If you prefer the composed key to be uppercased too, then we can change that, but we should then change  it on all composed key for the sake of consistency.

**Comment by cswertz** [comment]
OK. No need for changes in upper and lower cases. I'll add the unique keys from the model and vice versa.
