### ISSUE TITLE
Editor: Images placement error/Media Error

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#121]
When adding an image in the editor the text is correctly aligned. But after saving, the image is always placed above the text, not beside the text as in the editor. 

When adding a youtube link, the video is shown in the editor, but does not show up after the test is saved. 

BTW: Jumping thourgh versions works perfectly.

**Comment by stylesuxx** [comment]
Yes, I think we discussed this briefly already: The styles are only included during editing, not when rendering the content. Adjusting this should fix the formatting issues. Since we were not final with what the editor should be able to do, I did not render and include the CSS yet.

Youtube link not showing up is definitely a bug.
