### ISSUE TITLE
Vocabulary for metadata is not used

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#127]
While editing or viewing Metadata from the taxonomy, slugs are presented for selections or when KUs are viewed, but not the entries from the vocabulary.
It seems that translations for the taxonomy can not be edited as well. Maybe a list of all system languages with the translation can be offered for editing when when editing a taxonomy term (the taxonomy translations should be complete).

**Comment by stylesuxx** [comment]
- [ ] show taxonomies in the users preferred language, if it is not set, show in default language (english)
- [ ] check form for editing taxonomies

Since we show the user his preferred language, what should be displayed if the taxonomy has not been translated to the users preferred language yet? Should we default back to englisch or should we continue to display the slug. Technically a Title is always asked from the user, and the first given title is used as the englisch title.

**Comment by cswertz** [comment]
Whatever is easier. If that doesn't matter, I'd think the slug as fallback might be a good idea, since I assume that the slug will still be shown in the taxonomy editor to select entries. Thus showing the slug makes it easier to find entries where translations are missing.
BTW: When adding a taxonomy entry, in my version only  a type (that is: the slug) is required, not a titel. I thus assume the first entry is thus the slug, not the first title. I can not edit or add titles at the moment at all IMHO.
