### ISSUE TITLE
Roles & Permissions

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#23]
I am not entirely sure if Roles and Permissions are up to date here and reflect the current DB model => https://docs.google.com/spreadsheets/d/1Sr8PPDi6yUbuH5sHGvHe2_wMgCzK39Cnk5Bgb_xmu5w/edit#gid=0

Could you please check? Also I would recomment translating the roles into EN. This has some time, but it would be great to have this as soon as I am done with the current milestone - I could then start adding the seeders accordingly.

**Comment by stylesuxx** [comment]
I have been thinking. Maybe it would be best if you just think about the roles. I have written a permission sheet for the Models I already created, I could publish that as a seperate table, this way we would have everything(up till now at least). and you would just have to adapt it once I add new permissions...

**Comment by cswertz** [comment]
OK. I'll edit Capabilities New. Two remarks: (1) The idea of the capabilities table is to allow admins to configure the system. Some admins, for example, might want to allow teachers to assign the role "teacher" to other teachers, while others don't want that. (2) For example the capability to edit the taxonomy can be attached to users, but it's not automatically available for all users. This can be implicitly expressed in the current table. It can also be explicit by adding roles like "TaxonomyEditor". I assume the first one is easier?

**Comment by stylesuxx** [comment]
Hmm, right now the role model is a general model. So, the User has the assigned roles in every context.

If I understand you correctly, you want two different role models. One that is in the general context of the whole webapp - So basically the Roles: Guest, User and Admin - with a general set of capabilities.

And then another role model in context of the Learning Units - the user who creates the Learning Unit is the admin of this learning unit and can assign different roles to different users in context of this learning Unit.
If this is the case, I suggest to add a relation to reflect the user Roles in a Learning Unit. And every Learning Unit gets its own set of Roles. This would allow the admin of the Learning Unit to create his own roles and assign available capabilities. We could provide a set of base Roles for each Learning Unit and the admin could expand on those.

**Comment by cswertz** [comment]
Well - no. Guest, User and Admin is fine for now. And we are not creating courses yet. If we do later on, we will have to add "teacher" and "learner" beside guest, user and admin. No problem.
One problem now: setting "public", "review" and "lectorate" to true since this would turn knowledge units into KUs that are visible to guests/public. We can add "reviewer" and "lector" as roles and allow them to set these bits. 
Second problem: Who is allowed to add the role "reviewer". Reviewers or admins? I tried to add these things. If these suggestions are OK, all other things I thought off will be possible too.

**Comment by stylesuxx** [comment]
OK, I understand - Your suggestions are totally OK with me. We are very flexible with the role and capability System here.

**Comment by cswertz** [comment]
Picking up the role change: I try to explain what I have in mind:
First, the role will depend on the context. In my own course I am a teacher (as soon as courses are there, of course). In other peoples courses I can be a learner. That will require the role "teacher" and "learner" in the  global roles. I  also can invite others as teachers to my course (that is: making them to owners as well) if I have the capability to invite others as teachers to own courses. I think that's OK so far. 
The idea of changing roles is picked up from moodle, where teachers can switch content in a course to  "invisible for learners". Thus the course looks different for teachers and learners. It's possible to change the role in the profile view and take a look at the course as it would look to students. I assume we can reach that easily later on when implementing courses: Changing the role to learner just means to change the role for that course. Thus the global role is not touched. I see different options how to express this without changing the current model. But since this is not relevant in the moment, we don't have to solve it right now. We can also drop the field from the log table. I'll change this in a moment.
