### ISSUE TITLE
Seeders: Add default values to Taxonomy and TaxonomyLanguage

### ISSUE THREAD

**Issue by cswertz** [cswertz/lerndorf#55]
- [x] KnowledgeUnits: Media Types
- [x] KnowledgeUnits: Knowledge Types
- [x] KnowledgeUnits: Relation Types
- [x] KnowledgeUnits: Lizenses
- [x] KnowledgeUnits: ScreenResolutions
- [x] KnowledgeUnits: CourseLevel (unclear, from goolge drive)

**Comment by cswertz** [comment]
I added the Vocabulary to Taxonomies and the Vocables to TaxonomyLanguages. I did not add the SQL commands.

**Comment by cswertz** [comment]
It seems the editor does not support language versions of taxonomy entries?!

**Comment by stylesuxx** [comment]
Check seeder - array is available but not written to DB.
Check translation of Taxonomies.

**Comment by stylesuxx** [comment]
Regarding translation of Taxonomies, there is a couple of things that we should discuss:
* When editing a Learning unit, tags may be added, technically this needs a field for the translation of the taxonomy - should there just be a field for the current language, or for all languages - or should the user only be able to add existing Taxonomies?
* When adding a taxonomy, should there be a field for all possible languages, and should it only be possible to save when all fields are filled?
* What happens if there is no translation for a given language for a taxonomy, should I still show the slug of the taxonomy?

**Comment by cswertz** [comment]
Tags are not part of the taxonomy. Tags are stored in LearningUnitTag where the language of the tag can be stored. They are related 1:n to LearningUnitLanguage. There the language is stored. That is: The user can only add tags in a language he used for a title in LearningUnitLanguage. 

For the taxonomy editor (which is not connected to this issue): There should be fields for all possible languages and you can save parts of them. That is for the last one: yes.

**Comment by stylesuxx** [comment]
There is a separate issue regarding the UI. Seeding now works.
