### ISSUE TITLE
Learning Units

### ISSUE THREAD

**Issue by stylesuxx** [cswertz/lerndorf#71]
* [x] Adding the same learning unit twice should not be possible (unique key on title?)
* [x] Tags should not be required
* [x] Display sub terms of terms when adding relation
* [ ] ~No option to enter the translation for the title~ (No multi lingo)
* [x] List Titles of Learning Units as Targets

**Comment by cswertz** [comment]
* No option to enter the translation for the title 
* Tags should NOT be required 
* When editing a Learning Unit Titles should be listed as targest. Now I can only choose a number which creates a "uhandled rejection SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed" which is not astonishing since learning unit -26 does not exist (BTW: No error message in the frontend)
* when setting a relation type subterms of "hierarchical" should be displayed as well

**Comment by cswertz** [comment]
Ah - and adding the same learning unit twice is not longer possible.

**Comment by stylesuxx** [comment]
Tags are not required - if you input a tag and hit add tag it will be added - other wise it will not be added

**Comment by cswertz** [comment]
@stylesuxx Adding Translations for Learning Units is not possible. Should be available when editing learning units above tags.

**Comment by cswertz** [comment]
@stylesuxx Setting relations between learning units is not possible - I do not get any of the existing LUs in "Search for a Learning unit"

**Comment by cswertz** [comment]
@stylesuxx Existing Tags are not shown when editing a Learning Unit. Tags can not be deleted.

**Comment by cswertz** [comment]
Title of Current Learning Unit is not shown in title bar when editing e learning unit

**Comment by stylesuxx** [comment]
Generally check if there is other edit masks that could need the title.

**Comment by stylesuxx** [comment]
* #106
